"""empty message

Revision ID: 05182d2b574a
Revises: 74564c00b127
Create Date: 2025-02-12 16:18:27.763539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05182d2b574a'
down_revision: Union[str, None] = '74564c00b127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_program')
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserEMail', sa.String(), nullable=True))
        batch_op.drop_column('UserEmail')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserEmail', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('UserEMail')

    op.create_table('_alembic_tmp_program',
    sa.Column('ProgramName', sa.VARCHAR(), nullable=False),
    sa.Column('UsedArea', sa.FLOAT(), nullable=False),
    sa.Column('ScrapFraction', sa.FLOAT(), nullable=False),
    sa.Column('MachineName', sa.VARCHAR(), nullable=False),
    sa.Column('PostDateTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('Material', sa.VARCHAR(), nullable=False),
    sa.Column('Thickness', sa.FLOAT(), nullable=False),
    sa.Column('SheetLength', sa.FLOAT(), nullable=False),
    sa.Column('SheetWidth', sa.FLOAT(), nullable=False),
    sa.Column('ArchivePacketID', sa.INTEGER(), nullable=False),
    sa.Column('TimeLineID', sa.INTEGER(), nullable=False),
    sa.Column('Comment', sa.TEXT(), nullable=False),
    sa.Column('UserName', sa.VARCHAR(), nullable=False),
    sa.Column('UserFirstName', sa.VARCHAR(), nullable=False),
    sa.Column('UserLastName', sa.VARCHAR(), nullable=False),
    sa.Column('LastLoginDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('program_status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('CuttingTimeProgram', sa.NUMERIC(), nullable=False),
    sa.Column('RepeatIDProgram', sa.VARCHAR(), nullable=False),
    sa.Column('PostedByUserID', sa.INTEGER(), nullable=False),
    sa.Column('PierceQtyProgram', sa.INTEGER(), nullable=False),
    sa.Column('UserEMail', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ProgramName')
    )
    # ### end Alembic commands ###
