"""empty message

Revision ID: 05b63c4d9eb0
Revises: b2309a934f3f
Create Date: 2025-02-28 10:08:54.308400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b63c4d9eb0'
down_revision: Union[str, None] = 'b2309a934f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programfiodoerassociation',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('fio_doer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fio_doer_id'], ['fiodoer.id'], name='fk_association_fio_doer_id'),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name='fk_association_program_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'fio_doer_id', name='uix_program_fio_doer')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_by_fio_doer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('SourceFileName', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key('fk_part_done_by_fio_doer_id', 'fiodoer', ['done_by_fio_doer_id'], ['id'])

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_to_ods', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('master_fio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_program_started', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('time_program_finished', sa.TIMESTAMP(), nullable=True))
        batch_op.alter_column('program_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('NEW', 'CREATED', 'UNASSIGNED', 'ASSIGNED', 'ACTIVE', 'CALCULATING', 'DONE', name='programstatus'),
               existing_nullable=False)
        # batch_op.drop_constraint("FK_program_fiodoer_id", type_='foreignkey')
        batch_op.create_foreign_key('fk_program_master_fio_id', 'fiodoer', ['master_fio_id'], ['id'])
        batch_op.drop_column('fio_doer_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fio_doer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_program_master_fio_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fiodoer', ['fio_doer_id'], ['id'])
        batch_op.alter_column('program_status',
               existing_type=sa.Enum('NEW', 'CREATED', 'UNASSIGNED', 'ASSIGNED', 'ACTIVE', 'CALCULATING', 'DONE', name='programstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('time_program_finished')
        batch_op.drop_column('time_program_started')
        batch_op.drop_column('master_fio_id')
        batch_op.drop_column('path_to_ods')

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_constraint('fk_part_done_by_fio_doer_id', type_='foreignkey')
        batch_op.drop_column('SourceFileName')
        batch_op.drop_column('done_by_fio_doer_id')

    op.drop_table('programfiodoerassociation')
    # ### end Alembic commands ###
