"""empty message

Revision ID: 077854ebffc8
Revises: e36ffaef4891
Create Date: 2025-02-14 10:50:21.557232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077854ebffc8'
down_revision: Union[str, None] = 'e36ffaef4891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_constraint('uq_part_program', type_='unique')
        batch_op.create_unique_constraint('uq_part_program_wo', ['PartName', 'program_id', 'wo_number_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_constraint('uq_part_program_wo', type_='unique')
        batch_op.create_unique_constraint('uq_part_program', ['PartName', 'program_id'])

    # ### end Alembic commands ###
