"""user-fio_doer one-to-one

Revision ID: 11f26e3faeed
Revises: 3448de858f05
Create Date: 2025-03-20 15:22:07.835012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f26e3faeed'
down_revision: Union[str, None] = '3448de858f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiodoer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uniq_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_fiodoer_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiodoer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fiodoer_user_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
