"""empty message

Revision ID: 146619e72f5b
Revises: 80f437d37481
Create Date: 2025-02-10 16:35:03.635965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146619e72f5b'
down_revision: Union[str, None] = '80f437d37481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.alter_column('RectArea',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('TrueWeight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('RectWeight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('CuttingLength',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('NestedArea',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.alter_column('NestedArea',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('CuttingLength',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('RectWeight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('TrueWeight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('RectArea',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
