"""empty message

Revision ID: 18e34a163b67
Revises: a5a3cdb12a21
Create Date: 2025-02-10 15:57:49.995070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e34a163b67'
down_revision: Union[str, None] = 'a5a3cdb12a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('ProgramName', sa.String(), nullable=False),
    sa.Column('RepeatID', sa.String(), nullable=False),
    sa.Column('UsedArea', sa.Float(), nullable=False),
    sa.Column('ScrapFraction', sa.Float(), nullable=False),
    sa.Column('MachineName', sa.String(), nullable=False),
    sa.Column('CuttingTime', sa.Numeric(), nullable=False),
    sa.Column('PierceQuantity', sa.Integer(), nullable=False),
    sa.Column('PostDateTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('Material', sa.String(), nullable=False),
    sa.Column('Thickness', sa.Float(), nullable=False),
    sa.Column('SheetLength', sa.Float(), nullable=False),
    sa.Column('SheetWidth', sa.Float(), nullable=False),
    sa.Column('ArchivePacketID', sa.Integer(), nullable=False),
    sa.Column('TimeLineID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.TEXT(), nullable=False),
    sa.Column('PostByUserID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=False),
    sa.Column('UserFirstName', sa.String(), nullable=False),
    sa.Column('UserLastName', sa.String(), nullable=False),
    sa.Column('UserEmail', sa.String(), nullable=False),
    sa.Column('LastLoginDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('program_status', sa.Enum('CREATED', 'UNASSIGNED', 'ASSIGNED', 'ACTIVE', 'DONE', 'ARCHIVED', name='programstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ProgramName')
    )
    op.create_table('wo',
    sa.Column('WONumber', sa.String(), nullable=False),
    sa.Column('CustomerName', sa.String(), nullable=False),
    sa.Column('WODate', sa.TIMESTAMP(), nullable=True),
    sa.Column('OrderDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('WOData1', sa.String(), nullable=True),
    sa.Column('WOData2', sa.String(), nullable=True),
    sa.Column('DateCreated', sa.TIMESTAMP(), nullable=False),
    sa.Column('wo_status', sa.Enum('CREATED', 'ACTIVE', 'FINISHED', name='wostatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('WONumber')
    )
    op.create_table('part',
    sa.Column('wo_numer_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('PartName', sa.String(), nullable=False),
    sa.Column('RepeatID', sa.Integer(), nullable=True),
    sa.Column('QtyInProcess', sa.Integer(), nullable=False),
    sa.Column('PartLength', sa.Float(), nullable=False),
    sa.Column('PartWidth', sa.Float(), nullable=False),
    sa.Column('TrueArea', sa.Float(), nullable=False),
    sa.Column('RectArea', sa.Float(), nullable=False),
    sa.Column('TrueWeight', sa.Float(), nullable=False),
    sa.Column('RectWeight', sa.Float(), nullable=False),
    sa.Column('CuttingTime', sa.Numeric(), nullable=False),
    sa.Column('CuttingLength', sa.Float(), nullable=False),
    sa.Column('PierceQty', sa.Integer(), nullable=False),
    sa.Column('NestedArea', sa.Float(), nullable=False),
    sa.Column('TotalCuttingTime', sa.Numeric(), nullable=False),
    sa.Column('MasterPartQty', sa.Integer(), nullable=False),
    sa.Column('WOState', sa.String(), nullable=False),
    sa.Column('DueDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('RevisionNumber', sa.String(), nullable=False),
    sa.Column('part_status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'DONE_PARTIAL', 'DONE_FULL', name='partstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['wo_numer_id'], ['wo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    op.drop_table('wo')
    op.drop_table('program')
    # ### end Alembic commands ###
