"""empty message

Revision ID: 1a7bd479f72a
Revises: f1791e611b42
Create Date: 2025-03-19 14:48:32.765127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7bd479f72a'
down_revision: Union[str, None] = 'f1791e611b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('USER', 'ADMIN', 'TECHMAN', 'MASTER', 'OPERATOR', 'LOGIST', name='userrole'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
