"""empty message

Revision ID: 2938518e2109
Revises: 146619e72f5b
Create Date: 2025-02-10 16:58:50.515376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2938518e2109'
down_revision: Union[str, None] = '146619e72f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RepeatIDPart', sa.Integer(), nullable=True))
        batch_op.drop_column('RepeatID')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RepeatIDProgram', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('PierceQty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('PostedByUserID', sa.Integer(), nullable=True))
        batch_op.alter_column('Thickness',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('PostByUserID')
        batch_op.drop_column('PierceQuantity')
        batch_op.drop_column('RepeatID')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RepeatID', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('PierceQuantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('PostByUserID', sa.INTEGER(), nullable=True))
        batch_op.alter_column('Thickness',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('PostedByUserID')
        batch_op.drop_column('PierceQty')
        batch_op.drop_column('RepeatIDProgram')

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RepeatID', sa.INTEGER(), nullable=True))
        batch_op.drop_column('RepeatIDPart')

    # ### end Alembic commands ###
