"""empty message

Revision ID: 4afb8eb438a1
Revises: bfbb95c1c103
Create Date: 2025-02-10 16:04:03.382652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afb8eb438a1'
down_revision: Union[str, None] = 'bfbb95c1c103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('CuttingTime',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('CuttingTime',
               existing_type=sa.NUMERIC(),
               nullable=False)

    # ### end Alembic commands ###
