"""empty message

Revision ID: 4babd986ca9a
Revises: 4afb8eb438a1
Create Date: 2025-02-10 16:05:34.480116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4babd986ca9a'
down_revision: Union[str, None] = '4afb8eb438a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('PierceQuantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('PierceQuantity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
