"""empty message

Revision ID: 54217ea6f71a
Revises: 7beffc0e8afa
Create Date: 2025-02-21 11:01:12.274966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54217ea6f71a'
down_revision: Union[str, None] = '7beffc0e8afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiodoer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiodoer', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
