"""remove uniqe from part

Revision ID: 6c46d88bec37
Revises: 11f26e3faeed
Create Date: 2025-06-05 11:24:07.593857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c46d88bec37'
down_revision: Union[str, None] = '11f26e3faeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_constraint('uq_part_program_wo', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_part_program_wo', ['PartName', 'program_id', 'wo_number_id'])

    # ### end Alembic commands ###
