"""empty message

Revision ID: 74564c00b127
Revises: eb67fd457512
Create Date: 2025-02-11 16:52:57.289879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74564c00b127'
down_revision: Union[str, None] = 'eb67fd457512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_part_program', ['PartName', 'program_id'])
        batch_op.drop_column('RepeatIDPart')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RepeatIDPart', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('uq_part_program', type_='unique')

    # ### end Alembic commands ###
