"""empty message

Revision ID: 80f437d37481
Revises: 9e003f505f27
Create Date: 2025-02-10 16:31:04.170252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f437d37481'
down_revision: Union[str, None] = '9e003f505f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('wo_number_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('PartName', sa.String(), nullable=False),
    sa.Column('RepeatID', sa.Integer(), nullable=True),
    sa.Column('QtyInProcess', sa.Integer(), nullable=False),
    sa.Column('PartLength', sa.Float(), nullable=False),
    sa.Column('PartWidth', sa.Float(), nullable=False),
    sa.Column('TrueArea', sa.Float(), nullable=False),
    sa.Column('RectArea', sa.Float(), nullable=False),
    sa.Column('TrueWeight', sa.Float(), nullable=False),
    sa.Column('RectWeight', sa.Float(), nullable=False),
    sa.Column('CuttingTimePart', sa.Numeric(), nullable=False),
    sa.Column('CuttingLength', sa.Float(), nullable=False),
    sa.Column('PierceQty', sa.Integer(), nullable=False),
    sa.Column('NestedArea', sa.Float(), nullable=False),
    sa.Column('TotalCuttingTime', sa.Numeric(), nullable=False),
    sa.Column('MasterPartQty', sa.Integer(), nullable=False),
    sa.Column('WOState', sa.String(), nullable=False),
    sa.Column('DueDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('RevisionNumber', sa.String(), nullable=False),
    sa.Column('PK_PIP', sa.String(), nullable=True),
    sa.Column('part_status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'DONE_PARTIAL', 'DONE_FULL', name='partstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['wo_number_id'], ['wo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    # ### end Alembic commands ###
