"""empty message

Revision ID: 830a122b0e20
Revises: 25e3d1174908
Create Date: 2025-02-10 17:05:21.847286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830a122b0e20'
down_revision: Union[str, None] = '25e3d1174908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('PierceQty')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PierceQty', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
