"""empty message

Revision ID: 9a99fe8bb82a
Revises: cce42c7a475c
Create Date: 2025-02-10 16:09:40.149747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a99fe8bb82a'
down_revision: Union[str, None] = 'cce42c7a475c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('PostByUserID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('PostByUserID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
