"""empty message

Revision ID: 9e003f505f27
Revises: b7e8caa4dc58
Create Date: 2025-02-10 16:29:29.429000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e003f505f27'
down_revision: Union[str, None] = 'b7e8caa4dc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PK_PIP', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_column('PK_PIP')

    # ### end Alembic commands ###
