"""empty message

Revision ID: a5a3cdb12a21
Revises: cda834de42e1
Create Date: 2025-02-07 16:14:00.629115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a3cdb12a21'
down_revision: Union[str, None] = 'cda834de42e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('repeat_id', sa.String(), nullable=False),
    sa.Column('user_area', sa.Float(), nullable=False),
    sa.Column('scrap_fraction', sa.Float(), nullable=False),
    sa.Column('machine_name', sa.String(), nullable=False),
    sa.Column('cutting_time', sa.Numeric(), nullable=False),
    sa.Column('pierce_qty', sa.Integer(), nullable=False),
    sa.Column('post_date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('sheet_length', sa.Float(), nullable=False),
    sa.Column('sheet_width', sa.Float(), nullable=False),
    sa.Column('archive_packet_id', sa.Integer(), nullable=False),
    sa.Column('time_line_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('post_by_user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_first_name', sa.String(), nullable=False),
    sa.Column('user_last_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_last_login_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('program_status', sa.Enum('CREATED', 'UNASSIGNED', 'ASSIGNED', 'ACTIVE', 'DONE', 'ARCHIVED', name='programstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wo',
    sa.Column('wo_number', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('wo_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('order_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('wo_data_1', sa.String(), nullable=True),
    sa.Column('wo_data_2', sa.String(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('wo_status', sa.Enum('CREATED', 'ACTIVE', 'FINISHED', name='wostatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('wo_numer_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=False),
    sa.Column('repeat_id', sa.Integer(), nullable=True),
    sa.Column('qty_in_process', sa.Integer(), nullable=False),
    sa.Column('part_length', sa.Float(), nullable=False),
    sa.Column('part_width', sa.Float(), nullable=False),
    sa.Column('true_area', sa.Float(), nullable=False),
    sa.Column('rect_area', sa.Float(), nullable=False),
    sa.Column('true_weight', sa.Float(), nullable=False),
    sa.Column('rect_weight', sa.Float(), nullable=False),
    sa.Column('cutting_time', sa.Numeric(), nullable=False),
    sa.Column('cutting_length', sa.Float(), nullable=False),
    sa.Column('pierce_qty', sa.Integer(), nullable=False),
    sa.Column('nested_area', sa.Float(), nullable=False),
    sa.Column('total_cutting_time', sa.Numeric(), nullable=False),
    sa.Column('master_part_qty', sa.Integer(), nullable=False),
    sa.Column('wo_state', sa.String(), nullable=False),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('revision_number', sa.String(), nullable=False),
    sa.Column('pk_pip', sa.String(), nullable=False),
    sa.Column('part_status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'DONE_PARTIAL', 'DONE_FULL', name='partstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['wo_numer_id'], ['wo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    op.drop_table('wo')
    op.drop_table('program')
    # ### end Alembic commands ###
