"""empty message

Revision ID: b2309a934f3f
Revises: 54217ea6f71a
Create Date: 2025-02-26 11:57:36.449981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2309a934f3f'
down_revision: Union[str, None] = '54217ea6f71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='programpriority'), server_default=sa.text('4'), nullable=False))
        batch_op.create_index(batch_op.f('ix_program_program_priority'), ['program_priority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_program_priority'))
        batch_op.drop_column('program_priority')

    # ### end Alembic commands ###
