"""empty message

Revision ID: b7e8caa4dc58
Revises: 9a99fe8bb82a
Create Date: 2025-02-10 16:14:47.865027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e8caa4dc58'
down_revision: Union[str, None] = '9a99fe8bb82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CuttingTimePart', sa.Numeric(), nullable=False))
        batch_op.drop_column('CuttingTime')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CuttingTimeProgram', sa.Numeric(), nullable=True))
        batch_op.drop_column('CuttingTime')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CuttingTime', sa.NUMERIC(), nullable=True))
        batch_op.drop_column('CuttingTimeProgram')

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CuttingTime', sa.NUMERIC(), nullable=False))
        batch_op.drop_column('CuttingTimePart')

    # ### end Alembic commands ###
