"""empty message

Revision ID: bfbb95c1c103
Revises: 18e34a163b67
Create Date: 2025-02-10 16:02:04.762147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbb95c1c103'
down_revision: Union[str, None] = '18e34a163b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('RepeatID',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('RepeatID',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
