"""empty message

Revision ID: cce42c7a475c
Revises: 4babd986ca9a
Create Date: 2025-02-10 16:07:32.608905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce42c7a475c'
down_revision: Union[str, None] = '4babd986ca9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('Thickness',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('Thickness',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
