"""empty message

Revision ID: e36ffaef4891
Revises: 
Create Date: 2025-02-14 09:43:24.441190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36ffaef4891'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wo',
    sa.Column('WONumber', sa.String(), nullable=False),
    sa.Column('CustomerName', sa.String(), nullable=False),
    sa.Column('WODate', sa.TIMESTAMP(), nullable=False),
    sa.Column('OrderDate', sa.TIMESTAMP(), nullable=False),
    sa.Column('WOData1', sa.String(), nullable=True),
    sa.Column('WOData2', sa.String(), nullable=True),
    sa.Column('DateCreated', sa.TIMESTAMP(), nullable=False),
    sa.Column('wo_status', sa.Enum('CREATED', 'ACTIVE', 'FINISHED', name='wostatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wo_WONumber'), ['WONumber'], unique=True)
        batch_op.create_index(batch_op.f('ix_wo_wo_status'), ['wo_status'], unique=False)

    op.create_table('program',
    sa.Column('ProgramName', sa.String(), nullable=False),
    sa.Column('RepeatIDProgram', sa.String(), nullable=False),
    sa.Column('UsedArea', sa.Float(), nullable=False),
    sa.Column('ScrapFraction', sa.Float(), nullable=False),
    sa.Column('MachineName', sa.String(), nullable=False),
    sa.Column('CuttingTimeProgram', sa.Numeric(), nullable=False),
    sa.Column('PostDateTime', sa.TIMESTAMP(), nullable=False),
    sa.Column('Material', sa.String(), nullable=False),
    sa.Column('Thickness', sa.Float(), nullable=False),
    sa.Column('SheetLength', sa.Float(), nullable=False),
    sa.Column('SheetWidth', sa.Float(), nullable=False),
    sa.Column('ArchivePacketID', sa.Integer(), nullable=False),
    sa.Column('TimeLineID', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.TEXT(), nullable=False),
    sa.Column('PostedByUserID', sa.Integer(), nullable=False),
    sa.Column('PierceQtyProgram', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=False),
    sa.Column('UserFirstName', sa.String(), nullable=False),
    sa.Column('UserLastName', sa.String(), nullable=False),
    sa.Column('UserEMail', sa.String(), nullable=True),
    sa.Column('LastLoginDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('program_status', sa.Enum('NEW', 'CREATED', 'UNASSIGNED', 'ASSIGNED', 'ACTIVE', 'DONE', 'ARCHIVED', name='programstatus'), nullable=False),
    sa.Column('fio_doer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fio_doer_id'], ['fiodoer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_ProgramName'), ['ProgramName'], unique=True)
        batch_op.create_index(batch_op.f('ix_program_program_status'), ['program_status'], unique=False)

    op.create_table('part',
    sa.Column('wo_number_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('PartName', sa.String(), nullable=False),
    sa.Column('QtyInProcess', sa.Integer(), nullable=False),
    sa.Column('PartLength', sa.Float(), nullable=False),
    sa.Column('PartWidth', sa.Float(), nullable=False),
    sa.Column('TrueArea', sa.Float(), nullable=False),
    sa.Column('RectArea', sa.Float(), nullable=False),
    sa.Column('TrueWeight', sa.Float(), nullable=False),
    sa.Column('RectWeight', sa.Float(), nullable=False),
    sa.Column('CuttingTimePart', sa.Numeric(), nullable=False),
    sa.Column('CuttingLength', sa.Float(), nullable=False),
    sa.Column('PierceQtyPart', sa.Integer(), nullable=False),
    sa.Column('NestedArea', sa.Float(), nullable=False),
    sa.Column('TotalCuttingTime', sa.Numeric(), nullable=False),
    sa.Column('MasterPartQty', sa.Integer(), nullable=False),
    sa.Column('WOState', sa.String(), nullable=False),
    sa.Column('DueDate', sa.TIMESTAMP(), nullable=False),
    sa.Column('RevisionNumber', sa.String(), nullable=False),
    sa.Column('PK_PIP', sa.String(), nullable=False),
    sa.Column('part_status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'DONE_PARTIAL', 'DONE_FULL', name='partstatus'), nullable=False),
    sa.Column('Thickness', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['wo_number_id'], ['wo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PartName', 'program_id', name='uq_part_program')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_PartName'), ['PartName'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_part_status'), ['part_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_part_status'))
        batch_op.drop_index(batch_op.f('ix_part_PartName'))

    op.drop_table('part')
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_program_status'))
        batch_op.drop_index(batch_op.f('ix_program_ProgramName'))

    op.drop_table('program')
    with op.batch_alter_table('wo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wo_wo_status'))
        batch_op.drop_index(batch_op.f('ix_wo_WONumber'))

    op.drop_table('wo')
    # ### end Alembic commands ###
