"""empty message

Revision ID: eb67fd457512
Revises: 830a122b0e20
Create Date: 2025-02-11 09:08:19.263898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb67fd457512'
down_revision: Union[str, None] = '830a122b0e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PierceQtyPart', sa.Integer(), nullable=False))
        batch_op.alter_column('RectArea',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('TrueWeight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('RectWeight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('CuttingLength',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('NestedArea',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('DueDate',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('PK_PIP',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_part_PartName'), ['PartName'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_part_status'), ['part_status'], unique=False)
        batch_op.drop_column('PierceQty')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PierceQtyProgram', sa.Integer(), nullable=False))
        batch_op.alter_column('CuttingTimeProgram',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('PostedByUserID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_program_ProgramName'), ['ProgramName'], unique=True)
        batch_op.create_index(batch_op.f('ix_program_program_status'), ['program_status'], unique=False)

    with op.batch_alter_table('wo', schema=None) as batch_op:
        batch_op.alter_column('WODate',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('OrderDate',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_wo_WONumber'), ['WONumber'], unique=True)
        batch_op.create_index(batch_op.f('ix_wo_wo_status'), ['wo_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wo_wo_status'))
        batch_op.drop_index(batch_op.f('ix_wo_WONumber'))
        batch_op.alter_column('OrderDate',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('WODate',
               existing_type=sa.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_program_status'))
        batch_op.drop_index(batch_op.f('ix_program_ProgramName'))
        batch_op.alter_column('PostedByUserID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('CuttingTimeProgram',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.drop_column('PierceQtyProgram')

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PierceQty', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_part_part_status'))
        batch_op.drop_index(batch_op.f('ix_part_PartName'))
        batch_op.alter_column('PK_PIP',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('DueDate',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('NestedArea',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('CuttingLength',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('RectWeight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('TrueWeight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('RectArea',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('PierceQtyPart')

    # ### end Alembic commands ###
