"""empty message

Revision ID: ede32ef40408
Revises: 05b63c4d9eb0
Create Date: 2025-02-28 10:29:42.340172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede32ef40408'
down_revision: Union[str, None] = '05b63c4d9eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('ProgramName',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('RepeatIDProgram',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('UsedArea',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('ScrapFraction',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('MachineName',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('CuttingTimeProgram',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('PostDateTime',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('Material',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('Thickness',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('SheetLength',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('SheetWidth',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('ArchivePacketID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('TimeLineID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Comment',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('PostedByUserID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('PierceQtyProgram',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('UserName',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('UserFirstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('UserLastName',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('program_status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('program_priority',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text('4'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_program_ProgramName'), ['ProgramName'], unique=True)
        batch_op.create_index(batch_op.f('ix_program_program_priority'), ['program_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_program_status'), ['program_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_program_status'))
        batch_op.drop_index(batch_op.f('ix_program_program_priority'))
        batch_op.drop_index(batch_op.f('ix_program_ProgramName'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('program_priority',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text('4'))
        batch_op.alter_column('program_status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('UserLastName',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('UserFirstName',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('UserName',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('PierceQtyProgram',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('PostedByUserID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('TimeLineID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ArchivePacketID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('SheetWidth',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('SheetLength',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('Thickness',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('Material',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('PostDateTime',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('CuttingTimeProgram',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('MachineName',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ScrapFraction',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('UsedArea',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('RepeatIDProgram',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ProgramName',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
